travis:
  secure:
    BINSTAR_TOKEN: tLdtjmfSRIeGYydwr0VYUlkRPU9R2lynG4Du13TXjUKrJm8b0dqruFP39FZYp0POdeyf7PXa2s47oIHfnWbMeerzZ7BCdc+GYrYR+W/1q3K5LSIHGYHm4gWyYVbKkLhbnjCBfZVJdjzasb9/DBlM5pLXc3fnJrpGnhPfwhnVhmdOC3cqBCmR2+oQjPYrIpX77YBGrZAjArLTbtg/q0EON8qap+7SEcZAW5yaLnjFi9bkoa6PFD86xsWtgF4S4h75Kwslx84WhV6R+qW9jDo2Q/CBysO369bKXS8WSgXxCJ/BIa4Fpt0rlDhtzFM841/f81ISp43lbjhyayk98Uv/+ArJgXm0pbzSShJl3Wr4OZgdeGIfCuqC/MZ7OPAGBMJjD7h1QjqgBOC4lUXm0KQZzFfAHSnshhx7uHzhJV6j9vlIM4BEOrjLrHcmi6CMGiLH5VJ+tNhj9q54YWmxq3XZwdHvAYyhNy5jKDY/Xu3J4TFJMwHIV83Z4GZy6GCgJmtjDcRJGdBNdQekP++aiTx/IzKv/cALSl6DHKJa3Rb4kBduN7q+pPcuR2n7O34monPLCicxagvHRWgesZvb1/qIhWWzU7yOJ23XYLlp/EcBWjRbqXDmJ1YonpeVtRZFwwgYiTPsx550njqmt0Cm+XJsgSp16alNW88hRiHOs9PFHy4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
